import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { mkdtempDisposable, readFile, type DisposableTempDir } from "fs/promises";
import { dirExists } from "@/utils/fs";
import { join } from "path";
import { tmpdir } from "os";
import { contextFactory } from "./context";
import type { CommentType } from "@/utils/codegen";

describe("path resolution", () => {
  const root = "/project";

  test("string default: resolved relative to root", () => {
    const Ctx = contextFactory({}, { paths: { sourceDir: "./src" } });
    const ctx = new Ctx({ root });
    expect(ctx.resolve("sourceDir")).toBe("/project/src");
  });

  test("string default: absolute path returned as-is", () => {
    const Ctx = contextFactory({}, { paths: { sourceDir: "/abs/src" } });
    const ctx = new Ctx({ root });
    expect(ctx.resolve("sourceDir")).toBe("/abs/src");
  });

  test("string default: overridden by user option", () => {
    const Ctx = contextFactory({}, { paths: { sourceDir: "./src" } });
    const ctx = new Ctx({ root, sourceDir: "./lib" });
    expect(ctx.resolve("sourceDir")).toBe("/project/lib");
  });

  test("tuple default: resolved relative to named path", () => {
    const Ctx = contextFactory(
      {},
      {
        paths: {
          sourceDir: "./src",
          testDir: ["sourceDir", "__tests__"],
        },
      },
    );
    const ctx = new Ctx({ root });
    expect(ctx.resolve("testDir")).toBe("/project/src/__tests__");
  });

  test("tuple default: follows override of base path", () => {
    const Ctx = contextFactory(
      {},
      {
        paths: {
          sourceDir: "./src",
          testDir: ["sourceDir", "__tests__"] as const,
        },
      },
    );
    const ctx = new Ctx({ root, sourceDir: "./lib" });
    expect(ctx.resolve("testDir")).toBe("/project/lib/__tests__");
  });
});

describe("options resolution", () => {
  const root = "/project";

  test("option default used when not overridden", () => {
    const Ctx = contextFactory({ serve: "/docs/" as string | false }, { paths: {} });
    const ctx = new Ctx({ root });
    expect(ctx.options.serve).toBe("/docs/");
  });

  test("option default overridden by user value", () => {
    const Ctx = contextFactory({ serve: "/docs/" as string | false }, { paths: {} });
    const ctx = new Ctx({ root, serve: false });
    expect(ctx.options.serve).toBe(false);
  });

  test("multiple options: partial override leaves other defaults intact", () => {
    const Ctx = contextFactory({ serve: "/docs/" as string | false, minify: false }, { paths: {} });
    const ctx = new Ctx({ root, serve: "/custom/" });
    expect(ctx.options.serve).toBe("/custom/");
    expect(ctx.options.minify).toBe(false);
  });

  test("paths-only factory call is backwards compatible", () => {
    const Ctx = contextFactory({}, { paths: { sourceDir: "./src" } });
    const ctx = new Ctx({ root });
    expect(ctx.resolve("sourceDir")).toBe("/project/src");
  });
});

class Context extends contextFactory({}, { paths: {} }) {
  generator = {
    name: "foo",
    version: "1.2.3",
  };
}
describe("Context file generation", () => {
  let tmp: DisposableTempDir;
  beforeAll(async () => {
    tmp = await mkdtempDisposable(join(tmpdir(), "test-"));
    expect(dirExists(tmp.path)).toBe(true);
  });

  afterAll(async () => {
    await tmp.remove();
  });

  test("Generator headers", async () => {
    const filePath = join(tmp.path, "foo.ts");
    const ctx = new Context({
      // root is not used in this test
      root: tmp.path,
    });
    await ctx.writeAutoGeneratedFile(filePath, "console.log('hey')", { commentType: "//" });

    const written = await readFile(filePath, { encoding: "utf-8" });
    expect(written).toMatch(/Generated by foo v1.2.3/);
  });

  test("Auto-detect comment type", async () => {
    const ctx = new Context({
      // root is not used in this test
      root: tmp.path,
    });

    const patterns = {
      xml: /^<!--/,
      "//": /^\/\//,
      "#": /^#/,
    };
    async function check(filename: string, expectedType: CommentType) {
      const filePath = join(tmp.path, filename);
      await ctx.writeAutoGeneratedFile(filePath, "");
      const written = await readFile(filePath, { encoding: "utf-8" });

      expect(written).toMatch(patterns[expectedType]);
    }

    await check("foo.ts", "//");
    await check("foo.md", "xml");
    await check("foo.sh", "#");
    await check(".gitignore", "#");

    await expect(check("foo.xyz", "#")).rejects.toThrowError(
      `Can't resolve comment type for path "${tmp.path}/foo.xyz"`,
    );
  });
});
