import path from "path";
import { readFile } from "fs/promises";
import { ZPackageJson } from "@/utils/package-json";
import {
  resolveCommentType,
  writeAutoGeneratedFile,
  writeDefaultFile,
  type CodeGenContext,
} from "@/utils/codegen";
import { resolvePackageMeta } from "../package-meta/client";

type PathDefault<PathNames extends string> =
  /** default relative to root */
  | string
  /** default relative to another named path, e.g. `["sourceDir", "__tests__"]` */
  | readonly [PathNames, string];

type PathDefaults<PathNames extends string> = {
  [Name in PathNames]: PathDefault<PathNames>;
};

/** What the user passes to the context constructor. All path and option keys are optional overrides. */
export type ContextInput<Paths, Opts> = { root: string } & { [K in keyof Paths]?: string } & {
  [K in keyof Opts]?: Opts[K];
};

/** What `ctx.options` holds after construction. Path overrides are still optional; option defaults have been applied. */
export type ContextResolved<Paths, Opts> = { root: string } & {
  [K in keyof Paths]?: string;
} & Opts;

function resolveBase<Paths, Opts>(
  defaults: PathDefaults<keyof Paths & string>,
  options: ContextResolved<Paths, Opts>,
  base: (keyof Paths & string) | "root",
) {
  if (base === "root") return options.root;
  let basePath: string | undefined = (options as Record<string, string | undefined>)[
    base as string
  ];
  if (typeof basePath === "undefined") {
    const pathDefault = defaults[base as keyof Paths & string];
    if (Array.isArray(pathDefault)) {
      const [baseName, relative] = pathDefault as readonly [keyof Paths & string, string];
      basePath = path.resolve(resolveBase<Paths, Opts>(defaults, options, baseName), relative);
    } else {
      basePath = pathDefault as string;
    }
  }
  if (path.isAbsolute(basePath)) {
    return basePath;
  } else {
    return path.resolve(options.root, basePath);
  }
}

class VitePluginContext<Paths, Opts> {
  constructor(public readonly options: ContextResolved<Paths, Opts>) {}

  /**
   * Defines the generator info used when calling {@link VitePluginContext.writeAutoGeneratedFile} and {@link VitePluginContext.writeDefaultFile}
   * You can (and should) override this when extending context
   * */
  generator: CodeGenContext["generator"] = resolvePackageMeta();

  /** resolves a base path using options or defaults */
  // oxlint-disable-next-line no-unused-vars
  resolveBase(base: (keyof Paths & string) | "root"): string {
    // using an abstract class for VitePluginContext didn't work
    // because the class return by the factory function is marked as abstract which is odd
    throw new Error("not implemented: please use contextFactory");
  }

  /**
   * @param base
   * @param paths
   * @returns Absolute path to desired resource
   */
  resolve(base: (keyof Paths & string) | "root", ...paths: string[]) {
    const basePath = this.resolveBase(base);
    return path.resolve(basePath, ...paths);
  }

  async resolvePackageJson() {
    const content = await readFile(this.resolve("root", "package.json"), {
      encoding: "utf8",
    });
    const json = JSON.parse(content);
    return await ZPackageJson.parseAsync(json);
  }

  async writeAutoGeneratedFile(file: string, content: string, ctx?: Partial<CodeGenContext>) {
    return writeAutoGeneratedFile(file, content, {
      generator: ctx?.generator ?? this.generator,
      commentType: ctx?.commentType ?? resolveCommentType(file, true),
    });
  }

  async writeDefaultFile(
    file: string,
    content: string,
    options?: Parameters<typeof writeDefaultFile>[2],
    ctx?: Partial<CodeGenContext>,
  ) {
    return writeDefaultFile(file, content, options, {
      generator: ctx?.generator ?? this.generator,
      commentType: ctx?.commentType ?? resolveCommentType(file, true),
    });
  }
}
export type { VitePluginContext };

type NoOverlap<Opts, Paths> = keyof Opts & keyof Paths & string extends never
  ? unknown
  : { readonly "Error: options and paths share key names": keyof Opts & keyof Paths & string };

/**
 * Creates a typed `VitePluginContext` subclass with custom options and named paths.
 *
 * @param opts   Plugin option defaults. Keys become non-optional on `ctx.options` with their
 *               inferred type (e.g. `string | false`). Pass `{}` when you have no options.
 * @param config Factory configuration.
 * @param config.paths Named path defaults, resolved relative to `root` (or another named path).
 *   - **String default** — resolved relative to `root`:
 *     ```ts
 *     contextFactory({}, { paths: { sourceDir: "./src" } })
 *     // ctx.resolve("sourceDir") → "<root>/src"
 *     ```
 *   - **Tuple default** — resolved relative to another named path:
 *     ```ts
 *     contextFactory({}, { paths: { sourceDir: "./src", testDir: ["sourceDir", "__tests__"] } })
 *     // ctx.resolve("testDir") → "<root>/src/__tests__"
 *     ```
 *     The tuple `["baseName", "relative"]` follows overrides: if the user overrides `sourceDir`,
 *     `testDir` resolves relative to the new value.
 *
 * Path keys and option keys must not overlap — TypeScript will error on the second argument if
 * they share a name.
 *
 * @example
 * ```ts
 * const MyContext = contextFactory(
 *   { serve: "/docs/" as string | false },
 *   { paths: { sourceDir: "./src", docsDir: "./docs" } },
 * );
 *
 * class Context extends MyContext {
 *   generator = { name: "my-plugin", version: "1.0.0" };
 * }
 *
 * const ctx = new Context({ root: config.root, serve: false });
 * ctx.options.serve      // false
 * ctx.options.sourceDir  // string | undefined
 * ctx.resolve("docsDir") // "<root>/docs"
 * ```
 */
export function contextFactory<
  Opts extends Record<string, unknown>,
  Paths extends PathDefaults<keyof Paths & string>,
>(
  opts: Opts,
  config: { paths: Paths } & NoOverlap<Opts, Paths>,
): new (input: ContextInput<Paths, Opts>) => VitePluginContext<Paths, Opts> {
  type P = keyof Paths & string;
  const { paths: pathDefaults } = config;
  return class Context extends VitePluginContext<Paths, Opts> {
    constructor(input: ContextInput<Paths, Opts>) {
      super({ ...opts, ...input } as ContextResolved<Paths, Opts>);
    }
    resolveBase(base: P | "root") {
      return resolveBase<Paths, Opts>(pathDefaults as PathDefaults<P>, this.options, base);
    }
  };
}

/** Extracts the union of path names from a `VitePluginContext` instance or class. */
export type getPathMap<C> =
  C extends VitePluginContext<infer Paths, infer _Opts> ? keyof Paths & string : never;

/** Extracts the resolved options type (`ctx.options`) from a `VitePluginContext` instance or class. */
export type contextOptions<C> =
  // oxlint-disable-next-line no-unused-vars
  C extends VitePluginContext<infer _Paths, infer _Opts> ? C["options"] : never;

export class DefaultVitePluginContext extends contextFactory(
  {},
  {
    paths: { sourceDir: "./src" },
  },
) {}
