import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { mkdtempDisposable, readFile, type DisposableTempDir } from "fs/promises";
import { dirExists } from "@/utils/fs";
import { join } from "path";
import { tmpdir } from "os";
import { contextFactory } from "./context";
import type { CommentType } from "@/utils/codegen";

class Context extends contextFactory({ paths: {} }) {
  generator = {
    name: "foo",
    version: "1.2.3",
  };
}
describe("Context file generation", () => {
  let tmp: DisposableTempDir;
  beforeAll(async () => {
    tmp = await mkdtempDisposable(join(tmpdir(), "test-"));
    expect(dirExists(tmp.path)).toBe(true);
  });

  afterAll(async () => {
    await tmp.remove();
  });

  test("Generator headers", async () => {
    const filePath = join(tmp.path, "foo.ts");
    const ctx = new Context({
      // root is not used in this test
      root: tmp.path,
    });
    await ctx.writeAutoGeneratedFile(filePath, "console.log('hey')", { commentType: "//" });

    const written = await readFile(filePath, { encoding: "utf-8" });
    expect(written).toMatch(/Generated by foo v1.2.3/);
  });

  test("Auto-detect comment type", async () => {
    const ctx = new Context({
      // root is not used in this test
      root: tmp.path,
    });

    const patterns = {
      xml: /^<!--/,
      "//": /^\/\//,
      "#": /^#/,
    };
    async function check(filename: string, expectedType: CommentType) {
      const filePath = join(tmp.path, filename);
      await ctx.writeAutoGeneratedFile(filePath, "");
      const written = await readFile(filePath, { encoding: "utf-8" });

      expect(written).toMatch(patterns[expectedType]);
    }

    await check("foo.ts", "//");
    await check("foo.md", "xml");
    await check("foo.sh", "#");
    await check(".gitignore", "#");

    await expect(check("foo.xyz", "#")).rejects.toThrowError(
      `Can't resolve comment type for path "${tmp.path}/foo.xyz"`,
    );
  });
});
