import type { Plugin, ResolvedConfig } from "vite";
import { Application, type ProjectReflection, type TypeDocOptions } from "typedoc";
import { join, resolve } from "path";
import { mkdir, writeFile } from "fs/promises";

export const defaultPlugins = [
  async function typedocPluginMarkdown(app) {
    return import("typedoc-plugin-markdown").then((m) => m.load(app));
  },
  async function typedocVitePressTheme(app) {
    return import("typedoc-vitepress-theme").then((m) => m.load(app as any));
  },
] satisfies TypeDocOptions["plugin"];

export type Options = TypeDocOptions & {
  /**
   * Path to the VitePress docs root directory.
   * TypeDoc output lands in `<docsRoot>/reference/api/`.
   * @default `<vite root>/docs`
   */
  docsRoot?: string;
  /** path to source dir (default entryPoints are `<sourceDir>/**\/*.ts`)
   * @default `<docsRoot>/../src`
   */
  sourceDir?: string;
  /** a hook to mutate in place typedocs options */
  onOptions?: (options: TypeDocOptions) => Promise<void> | void;
  /** a hook to call custom logic after files are generated */
  onGenerated?: () => void | Promise<void>;
  /**
   * Write a `.gitignore` containing `*` inside the TypeDoc output directory so
   * that generated Markdown files are excluded from git automatically.
   * @default true
   */
  gitignore?: boolean;
};

/**
 * Bootstrap a TypeDoc application generating an API reference into `<docsRoot>/reference/api/`.
 * Override with the `out` TypeDoc option to change the output path.
 */
export async function bootstrapTypeDoc(docsRoot: string, options: Options = {}) {
  const { onOptions, sourceDir: userSourceDir, ...userTypedocOptions } = options;
  const root = resolve(docsRoot);
  const out = resolve(root, "reference", "api");
  const sourceDir = userSourceDir ?? resolve(root, "..", "src");

  const typedocOptions: TypeDocOptions = {
    entryPoints: [join(sourceDir, "**", "*.ts")],
    skipErrorChecking: true,
    plugin: [...defaultPlugins],
    out,
    readme: "none",
    alwaysCreateEntryPointModule: true,
    cleanOutputDir: true,
    router: "module",
    // avoid to make the console flicker in dev mode
    preserveWatchOutput: true,
    // TODO: proper deepmerge
    ...userTypedocOptions,
  };

  await onOptions?.(typedocOptions);
  const app = await Application.bootstrapWithPlugins(typedocOptions);
  return app;
}

/**
 * Vite plugin that generates a TypeDoc API reference as Markdown files.
 *
 * - **Build mode**: runs TypeDoc once after the bundle is written.
 * - **Build watch mode** (`vite build --watch`): starts TypeDoc in watch mode alongside Vite.
 * - **Dev mode** (`vite dev`): starts TypeDoc in watch mode so the API reference stays
 *   up-to-date while you iterate.
 *
 * ```ts
 * // vite.config.ts
 * import { TypeDocPlugin } from "marmotte/vite/typedoc"
 * export default defineConfig({ plugins: [TypeDocPlugin()] })
 * ```
 */
export function TypeDocPlugin(options: Options = {}) {
  const { docsRoot: userDocsRoot, onGenerated, gitignore = true, ...bootstrapOptions } = options;
  let config: ResolvedConfig;
  let app: Application;
  let watchStarted = false;

  const generate = async (project: ProjectReflection) => {
    console.info("🔄 Generating TypeDoc documentation...");
    await app.generateOutputs(project);
    if (gitignore) {
      const outDir = app.options.getValue("out") as string;
      await mkdir(outDir, { recursive: true });
      await writeFile(
        join(outDir, ".gitignore"),
        "# Auto-generated by marmotte/vite/typedoc — set gitignore: false to disable\n*\n",
      );
    }
    await onGenerated?.();
    console.info("✅ TypeDoc documentation generated!");
  };

  const startWatch = async () => {
    if (watchStarted) return;
    watchStarted = true;
    app.convertAndWatch((project) => generate(project));
  };

  return {
    name: "marmotte:typedoc",
    apply: () => !process.env.VITEST,
    async configResolved(resolvedConfig) {
      config = resolvedConfig;
      const docsRoot = userDocsRoot ?? resolve(config.root, "docs");
      app = await bootstrapTypeDoc(docsRoot, bootstrapOptions);
    },
    async buildStart() {
      // build --watch: start the typedoc watcher alongside vite's watcher
      if (config.command === "build" && config.build.watch) {
        await startWatch();
      }
    },
    async closeBundle() {
      // build (non-watch): run once after the bundle is written
      if (config.command === "build" && !config.build.watch) {
        const project = await app.convert();
        if (!project) throw new Error("TypeDoc project reflection is undefined");
        await generate(project);
      }
    },
    async configureServer() {
      await startWatch();
    },
  } satisfies Plugin;
}

export default TypeDocPlugin;
