import { CodeGenContext } from "./context";
import { comment } from "./format";

export function generatedBy(ctx: CodeGenContext) {
  const { name, version } = ctx.generator;
  return comment(`Generated by ${name} v${version}`, ctx.commentType);
}

/** A file having this line as first line will be assumed to be generated by this plugins and thus can be safely overwritten */
export function autoManagedFileHeaderFirstLine(ctx: CodeGenContext) {
  return comment("AUTOMATICALLY MANAGED", ctx.commentType);
}

/**
 * Comments to disable tools that are not suitable in automatically managed file
 *
 * empty string if not applicable (else block ends by a newline)
 * */
export function autoManagedFileDisableTools(ctx: CodeGenContext) {
  if (ctx.commentType === "//") {
    return `/* eslint-disable */
// biome-ignore lint: disable
// oxlint-disable
/* prettier-ignore */
`;
  }
  return "";
}

export function autoManagedFileHeader(ctx: CodeGenContext) {
  return `${autoManagedFileHeaderFirstLine(ctx)}
${autoManagedFileDisableTools(ctx)}${generatedBy(ctx)}
${comment("!! DO NOT MODIFY THIS FILE !!", ctx.commentType)}

`;
}

export function autoGeneratedDefaultFileHeader(ctx: CodeGenContext) {
  return `${comment(
    `This file is an automatically generated default you can edit it as you wan
If you delete this file, the default version might be re-generated on next build`,
    ctx.commentType,
  )}
${generatedBy(ctx)}

`;
}
