import { copyFile, readFile, writeFile } from "fs/promises";
import { fileExists } from "../fs";
import {
  autoManagedFileHeader,
  autoManagedFileHeaderFirstLine,
  autoGeneratedDefaultFileHeader,
} from "./header";
import { resolveContext } from "./context";

export * from "./context";
export * from "./format";
export * from "./header";

/**
 * Writes content to file. If a file is already present and doesn't look like automatically generated by this plugins,
 * creates a backup and warns the user
 * @param file
 * @param content
 */
export async function writeAutoGeneratedFile(
  file: string,
  content: string,
  ctx = resolveContext(file),
) {
  if (fileExists(file)) {
    const current = await readFile(file, { encoding: "utf8" });
    if (!current.startsWith(autoManagedFileHeaderFirstLine(ctx))) {
      // probably an old file
      const backupFile = file + ".backup";
      console.warn(`Backing up ${file} at ${backupFile}`);
      await copyFile(file, backupFile);
    }
  }
  await writeFile(file, autoManagedFileHeader(ctx) + content);
}

/**
 * Writes content to file if not already present.
 */
export async function writeDefaultFile(
  file: string,
  content: string,
  options?: {
    /** still writes even if file exists */
    force?: boolean;
    /** don't write the default header */
    noHeader?: boolean;
  },
  ctx = resolveContext(file),
) {
  if (!fileExists(file) || options?.force) {
    const header = options?.noHeader ? "" : autoGeneratedDefaultFileHeader(ctx);
    await writeFile(file, header + content);
  }
}
