import { resolve } from "path";
// can't use @ alias because this file is loaded when vite.config.ts is loaded
import {
  autoGeneratedDefaultFileHeader,
  indent,
  writeAutoGeneratedFile,
  writeDefaultFile,
} from "@/utils/codegen";
import { mkdir } from "fs/promises";
import { fileExists } from "@/utils/fs";
import type { Context } from "../context";

async function ensureVitePressDir(ctx: Context) {
  const vitePressDir = ctx.resolve("docsDir", ".vitepress");
  await mkdir(vitePressDir, { recursive: true });
  return vitePressDir;
}

export async function writeDefaultFiles(ctx: Context, force = false) {
  const vitePressDir = await ensureVitePressDir(ctx);

  await writeDefaultFile(
    resolve(vitePressDir, "config.ts"),
    `import { defineConfig } from "vitepress";

import base from "./auto.config";

export default defineConfig({
  ...base,
});
`,
    {
      force,
    },
  );

  await writeDefaultFile(
    ctx.resolve("docsDir", ".gitignore"),
    `# ignore default output dir
/dist

# ignore automatically generated markdown files (they can be re-generated when building)
/reference/api/
/reference/api.md
# also ignore the generated navigation json
/.vitepress/api-reference.navigation.json`,
    {
      force,
    },
    {
      commentType: "#",
      generator: ctx.generator,
    },
  );

  const pkg = await ctx.resolvePackageJson();

  await writeDefaultFile(
    ctx.resolve("docsDir", "index.md"),
    `---
${autoGeneratedDefaultFileHeader({ generator: ctx.generator, commentType: "#" })}
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "${pkg.name}"
  # text: ""
  tagline: "${pkg.description}"
  actions:
    # - theme: brand
    #   text: Markdown Examples
    #   link: /markdown-examples
    - theme: alt
      text: "API Reference"
      link: /reference/api/README

# features:
#   - title: Feature A
#     details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
#   - title: Feature B
#     details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
#   - title: Feature C
#     details: Lorem ipsum dolor sit amet, consectetur adipiscing elit
---`,
    {
      // file must start with `--` on first line so header is added manually with `defaultFileHeader("#")`
      noHeader: true,
      force,
    },
  );
}

export async function writeConfig(ctx: Context) {
  const vitePressDir = await ensureVitePressDir(ctx);

  const apiNavFile = resolve(vitePressDir, "api-reference.navigation.json");
  const hasAPIDocs = fileExists(apiNavFile);

  const pkg = await ctx.resolvePackageJson();
  await writeAutoGeneratedFile(
    resolve(vitePressDir, "auto.config.ts"),
    `import { defineConfig, DefaultTheme } from "vitepress";

${indent(
  `import { sidebarItemFromTypeDocNavigationJSON } from "marmotte/vite/plugins/docs/client"
import apiReferenceNavigation from "./api-reference.navigation.json"`,
  hasAPIDocs ? "" : "// ",
)}

const sidebar: DefaultTheme.Sidebar = {}

${indent(
  `export const apiReferenceSidebar = sidebarItemFromTypeDocNavigationJSON({
  title: "API Reference",
  children: apiReferenceNavigation
})
sidebar["/reference/"] = [{ ...apiReferenceSidebar, collapsed: false }]`,
  hasAPIDocs ? "" : "// ",
)}

export const themeConfig: DefaultTheme.Config = {
  // enable search by default
  search: {
    provider: "local",
  },
  sidebar
}

export default defineConfig({
  title: "${pkg.name}",
  themeConfig
});
`,
  );
}
