// This file is an automatically generated default you can edit it as you wan
// If you delete this file, the default version might be re-generated on next build
// Generated by marmotte v0.2.0

import { defineConfig } from "vitepress";
import Sidebar from "marmotte/vitepress/sidebar";
import pkg from "../../package.json";

export default async () => {
  return defineConfig({
    title: "marmotte",
    themeConfig: {
      // enable search by default
      search: {
        provider: "local",
      },
      nav: [{ text: `v${pkg.version}`, link: "https://www.npmjs.com/package/marmotte" }],
    },
    vite: {
      plugins: [Sidebar()],
    },
  });
};
