// This file is an automatically generated default you can edit it as you wan
// If you delete this file, the default version might be re-generated on next build
// Generated by marmotte v0.2.0

import { defineConfig } from "vitepress";
import { generateSidebar } from "marmotte/vitepress/sidebar";
import TypeDoc from "marmotte/vitepress/typedoc";

export default async () => {
  // use this auto sidebar instead of typedoc-sidebar.json
  // see https://www.typedoc-plugin-markdown.org/plugins/vitepress/quick-start#configure-navbar-and-sidebar
  console.log("generating sidebar..."); // this can take time
  const sidebar = generateSidebar({
    documentRootPath: "docs",
    collapsed: true,
    useFolderLinkFromIndexFile: true,
    useTitleFromFrontmatter: true,
    useTitleFromFileHeading: true,
    useFolderTitleFromIndexFile: true,
  });
  return defineConfig({
    title: "marmotte",
    themeConfig: {
      // enable search by default
      search: {
        provider: "local",
      },
      sidebar,
    },
    vite: {
      plugins: [
        // FIXME: as of today, the reference also includes test files
        TypeDoc({}),
      ],
    },
  });
};
