import { resolve } from "path";
// can't use @ alias because this file is loaded when vite.config.ts is loaded
import { autoGeneratedDefaultFileHeader, writeDefaultFile } from "@/utils/codegen";
import { mkdir } from "fs/promises";
import type { Context } from "./context";

async function ensureVitePressDir(ctx: Context) {
  const vitePressDir = ctx.resolve("docsDir", ".vitepress");
  await mkdir(vitePressDir, { recursive: true });
  return vitePressDir;
}

export async function writeDefaultFiles(ctx: Context, force = false) {
  const vitePressDir = await ensureVitePressDir(ctx);
  const pkg = await ctx.resolvePackageJson();

  await writeDefaultFile(
    resolve(vitePressDir, "config.ts"),
    `import { defineConfig } from "vitepress";
import Sidebar from "marmotte/vitepress/sidebar";

export default async () => {
  return defineConfig({
    title: "${pkg.name}",
    themeConfig: {
      // enable search by default
      search: {
        provider: "local",
      },
    },
    vite: {
      plugins: [
        Sidebar(),
      ]
    }
  });
}
`,
    {
      force,
    },
  );

  await writeDefaultFile(
    ctx.resolve("docsDir", ".gitignore"),
    `# ignore vitepress output dirs
/.vitepress/dist
/.vitepress/cache
`,
    {
      force,
    },
    {
      commentType: "#",
      generator: ctx.generator,
    },
  );

  await writeDefaultFile(
    ctx.resolve("docsDir", "index.md"),
    `---
${autoGeneratedDefaultFileHeader({ generator: ctx.generator, commentType: "#" })}
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "${pkg.name}"
  # text: ""
  tagline: "${pkg.description}"
  actions:
    # see https://vitepress.dev/reference/default-theme-home-page#hero-section
    - theme: alt
      text: "API Reference"
      link: /reference/api/
---`,
    {
      // file must start with `--` on first line so header is added manually with `defaultFileHeader("#")`
      noHeader: true,
      force,
    },
  );

  await ctx.writeDefaultFile(
    resolve(vitePressDir, "theme", "index.ts"),
    `import DefaultTheme from "vitepress/theme";

// see https://vitepress-sidebar.cdget.com/advanced-usage/multi-level-sidebar-with-indents
import "marmotte/vitepress/sidebar/indent.css";

export default DefaultTheme;`,
  );
}
