import { resolve } from "path";
// can't use @ alias because this file is loaded when vite.config.ts is loaded
import {
  autoGeneratedDefaultFileHeader,
  indent,
  writeAutoGeneratedFile,
  writeDefaultFile,
} from "@/utils/codegen";
import { mkdir } from "fs/promises";
import { fileExists } from "@/utils/fs";
import type { Context } from "./context";

async function ensureVitePressDir(ctx: Context) {
  const vitePressDir = ctx.resolve("docsDir", ".vitepress");
  await mkdir(vitePressDir, { recursive: true });
  return vitePressDir;
}

export async function writeDefaultFiles(ctx: Context, force = false) {
  const vitePressDir = await ensureVitePressDir(ctx);
  const pkg = await ctx.resolvePackageJson();

  await writeDefaultFile(
    resolve(vitePressDir, "config.ts"),
    `import { defineConfig } from "vitepress";
import { generateSidebar } from "marmotte/vitepress/sidebar";
import TypeDoc from "marmotte/vitepress/typedoc";

export default async () => {
  // use this auto sidebar instead of typedoc-sidebar.json
  // see https://www.typedoc-plugin-markdown.org/plugins/vitepress/quick-start#configure-navbar-and-sidebar
  console.log("generating sidebar..."); // this can take time
  const sidebar = generateSidebar({
    documentRootPath: "docs",
    collapsed: true,
    useFolderLinkFromIndexFile: true,
    useTitleFromFrontmatter: true,
    useTitleFromFileHeading: true,
    useFolderTitleFromIndexFile: true,
  });
  return defineConfig({
    title: "${pkg.name}",
    themeConfig: {
      // enable search by default
      search: {
        provider: "local",
      },
      sidebar
    },
    vite: {
      plugins: [
        TypeDoc({}),
      ]
    }
  });
}
`,
    {
      force,
    },
  );

  await writeDefaultFile(
    ctx.resolve("docsDir", ".gitignore"),
    `# ignore vitepress output dirs
/dist
/.vitepress/cache

# ignore automatically generated markdown files (they can be re-generated when building)
/reference/api/
`,
    {
      force,
    },
    {
      commentType: "#",
      generator: ctx.generator,
    },
  );

  await writeDefaultFile(
    ctx.resolve("docsDir", "index.md"),
    `---
${autoGeneratedDefaultFileHeader({ generator: ctx.generator, commentType: "#" })}
# https://vitepress.dev/reference/default-theme-home-page
layout: home

hero:
  name: "${pkg.name}"
  # text: ""
  tagline: "${pkg.description}"
  actions:
    # see https://vitepress.dev/reference/default-theme-home-page#hero-section
    - theme: alt
      text: "API Reference"
      link: /reference/api/
---`,
    {
      // file must start with `--` on first line so header is added manually with `defaultFileHeader("#")`
      noHeader: true,
      force,
    },
  );
}
